### ISSUE TITLE
test result isn't displayed in "chelou" case

### ISSUE THREAD

**Issue by mgodlewski** [pgrange/bash_unit#44] opened 2017-09-15 09:00 UTC
```
$ cat test_chelou 
test_version_installed() {
  version_found=0
  [ -x /opt/logstash/bin/logstash ] && version_found=1 && assert_equals "$(/opt/logstash/bin/logstash --version)" "logstash 2.3.4"
  [ -x /usr/share/logstash/bin/logstash ] && version_found=1 && assert_equals "$(/usr/share/logstash/bin/logstash --version)" "logstash 5.6.0"
  [ "$version_found" -eq 0 ] && fail "no version found"
}
```

Logstash not installed, works as expected
```
$ ./bash_unit test_chelou 
Running tests in test_chelou
Running test_version_installed... FAILURE ✗ 
no version found
test_chelou:5:test_version_installed()
```

_Fake logstash_
```
$ sudo mkdir -p /usr/share/logstash/bin/
$ sudo bash -c 'echo "echo logstash 5.6.0" > /usr/share/logstash/bin/logstash'
$ sudo chmod +x /usr/share/logstash/bin/logstash
$ ./bash_unit test_chelou 
Running tests in test_chelou
Running test_version_installed... 
```
Expected result
```
$ ./bash_unit test_chelou 
Running tests in test_chelou
Running test_version_installed... SUCCESS
```

**Comment by mgodlewski** [comment] 2017-09-15 12:39
Workaround
```
test_version_installed() {
  version_found=0
  expected_version=tbd
  [ -x /opt/logstash/bin/logstash ] && expected_version="logstash 2.3.4" && version_found="$(/opt/logstash/bin/logstash --version)"
  [ -x /usr/share/logstash/bin/logstash ] && expected_version="logstash 5.6.0" && version_found="$(/usr/share/logstash/bin/logstash --version)"
  assert_equals "$expected_version" "$version_found"
 }
```

**Comment by pgrange** [comment] 2017-09-22 06:40
Hi,

You can reproduce with a much simpler test:
```
test_chelou() {
  [ 2 -eq 3 ]
}
```

The result code of a bash function is the result code of the last instruction of the function. So in this case, the function test_chelou has a result code different from 0 since 2 is not equal to 3 or, in your actual case, since version_found is not equal to 0.

The result is that, from bash_unit perspective, your test failed, see the global bash_unit status code which is different from 0:

```
#> bash_unit /tmp/test_chelou
Running tests in /tmp/test_chelou
Running test_chelou... #> echo $?
1
```

So your test failed but you didn't rely on a bash_unit assertion function to make it fail. And since it is the job of the assertion function to store information about your test failure for it to be displayed in bash_unit output... you see this strange output.

Your workaround, is not so much a workaround to me: that is the good way to assert such things. If you really need to do such things as a test followed by an failure, you should handle the opportunity of your test itself to fail and ignore it with code like:

```
test_chelou() {
  [ 1 -eq 0 ] && fail || echo -n
}
```

In this case echo -n instruction is used as a kind of noop that does not fail and capture the equality failure so that your bash function itself does not fail:

```
#> bash_unit /tmp/test_chelou
Running tests in /tmp/test_chelou
Running test_chelou... SUCCESS ✓ 
```

I am not sure of what to do with that since it is quite a normal behavior in bash. But if you have an idea of something that would have helped you find your problem faster, I am interested.

**Comment by pgrange** [comment] 2017-11-10 07:16
Without answer, I close the issue but do not hesitate to re-open if you want to comment more.

Regards.

**Closed by pgrange** 2017-11-10 07:16 UTC

**Comment by mgodlewski** [comment] 2017-12-06 15:01
Thanks for this explanation. I wasn't aware of the standard behaviour. From now, I understand it well.
